---

- include: minecraft.yml
  when: minecraft_server == 'minecraft'

- include: spigot.yml
  when: minecraft_server == 'spigot'

- name: agree to EULA
  lineinfile:
    dest: "{{ deploy_helper.shared_path }}/eula.txt"
    regexp: '^eula='
    line: 'eula={{ minecraft_eula_accept | lower }}'
    create: true
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service

- name: check that log base directory exists
  file:
    path: "/var/log/minecraft"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755

 # https://help.minecraft.net/hc/en-us/articles/4416199399693-Security-Vulnerability-in-Minecraft-Java-Edition
- name: set the default log4j config name
  set_fact: 
    _log4j_default_template_file_name: log4j2.xml.j2

- name: set overwrite for special mc versions
  set_fact: 
    _log4j_default_template_file_name: log4j2_17-111.xml.j2
  when: (minecraft_version_int is version('1.7', '>=')) and (minecraft_version_int is version('1.11', '<='))

- name: external logging config
  template:
    src: "{{ minecraft_external_log_conf.template | default(_log4j_default_template_file_name) }}"
    dest: "{{ deploy_helper.shared_path }}/{{ minecraft_external_log_conf.conf_file | default('log4j2.xml') }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0600
  notify:
    - restart Minecraft
